source "https://rubygems.org"

gem "bourbon"
gem "middleman"
gem "middleman-favicon-maker"
gem "middleman-google-analytics"
gem "middleman-livereload"
gem "middleman-smusher"
gem "middleman-sync"
gem "middleman-syntax"
gem "neat"
gem "pry"
gem "pry-nav"
gem "unf"
